package(default_visibility = ["//visibility:public"])

pex_pytest(
    name = "component_unittest",
    srcs = ["component_unittest.py"],
    deps = [
      "//heronpy/api:heron-python-py",
    ],
    reqs = [
      "py==1.4.34",
      "pytest==3.2.2",
      "unittest2==1.1.0",
    ],
    size = "small",
)

pex_pytest(
    name = "stream_unittest",
    srcs = ["stream_unittest.py"],
    deps = [
      "//heronpy/api:heron-python-py",
    ],
    reqs = [
      "py==1.4.34",
      "pytest==3.2.2",
      "unittest2==1.1.0",
    ],
    size = "small",
)

pex_pytest(
    name = "topology_unittest",
    srcs = ["topology_unittest.py"],
    deps = [
      "//heronpy/api:heron-python-py",
    ],
    reqs = [
      "py==1.4.34",
      "pytest==3.2.2",
      "unittest2==1.1.0",
    ],
    size = "small",
)

pex_pytest(
    name = "serializer_unittest",
    srcs = ["serializer_unittest.py"],
    deps = [
      "//heronpy/api:heron-python-py",
    ],
    reqs = [
      "py==1.4.34",
      "pytest==3.2.2",
      "unittest2==1.1.0",
    ],
    size = "small",
)

pex_pytest(
    name = "metrics_unittest",
    srcs = ["metrics_unittest.py"],
    deps = [
      "//heronpy/api:heron-python-py",
    ],
    reqs = [
      "py==1.4.34",
      "pytest==3.2.2",
      "unittest2==1.1.0",
    ],
    size = "small",
)
