package(default_visibility = ["//visibility:public"])

pex_pytest(
    name = "component_unittest",
    size = "small",
    srcs = ["component_unittest.py"],
    reqs = [
        "py==1.4.34",
        "pytest==3.2.2",
        "unittest2==1.1.0",
    ],
    deps = [
        "//heronpy/api:heron-python-py",
    ],
)

pex_pytest(
    name = "stream_unittest",
    size = "small",
    srcs = ["stream_unittest.py"],
    reqs = [
        "py==1.4.34",
        "pytest==3.2.2",
        "unittest2==1.1.0",
    ],
    deps = [
        "//heronpy/api:heron-python-py",
    ],
)

pex_pytest(
    name = "topology_unittest",
    size = "small",
    srcs = ["topology_unittest.py"],
    reqs = [
        "py==1.4.34",
        "pytest==3.2.2",
        "unittest2==1.1.0",
    ],
    deps = [
        "//heronpy/api:heron-python-py",
    ],
)

pex_pytest(
    name = "serializer_unittest",
    size = "small",
    srcs = ["serializer_unittest.py"],
    reqs = [
        "py==1.4.34",
        "pytest==3.2.2",
        "unittest2==1.1.0",
    ],
    deps = [
        "//heronpy/api:heron-python-py",
    ],
)

pex_pytest(
    name = "metrics_unittest",
    size = "small",
    srcs = ["metrics_unittest.py"],
    reqs = [
        "py==1.4.34",
        "pytest==3.2.2",
        "unittest2==1.1.0",
    ],
    deps = [
        "//heronpy/api:heron-python-py",
    ],
)
