package(default_visibility = ["//visibility:public"])

sh_binary(
  name = "heron-downloader",
  srcs = ["heron-downloader.sh"],
)

sh_binary(
  name = "heron-downloader-config-kubernetes",
  srcs = ["heron-downloader-config-kubernetes.sh"],
)
