package(default_visibility = ["//visibility:public"])

sh_binary(
  name = "heron-downloader",
  srcs = ["heron-downloader.sh"],
)

#genrule(
#  name = "heron-downloader-sh",
#  srcs = [":heron-downloader.sh"],
#  outs = ["heron-downloader"],
#  cmd  = "cp $< $(OUTS)",
#)
