java_test(
    name = "exception_info_unittest",
    srcs = glob(["**/ExceptionInfoTest.java"]),
    deps = [
        "//heron/api/src/java:api-java", 
        "//heron/common/src/java:common-java", 
        "//heron/metricsmgr-api/src/java:metricsmgr-api-java", 
        "//heron/metricsmgr/src/java:metricsmgr-lib-java", 
        "//heron/proto:proto-java",
        "//3rdparty/protobuf:protobuf-java",
        "@bazel_tools//third_party:mockito",
        "@bazel_tools//third_party:junit4",
    ],
    size = "small",
)

java_test(
    name = "metrics_info_unittest",
    srcs = glob(["**/MetricsInfoTest.java"]),
    deps = [
        "//heron/api/src/java:api-java", 
        "//heron/common/src/java:common-java", 
        "//heron/metricsmgr-api/src/java:metricsmgr-api-java", 
        "//heron/metricsmgr/src/java:metricsmgr-lib-java", 
        "//heron/proto:proto-java",
        "//3rdparty/protobuf:protobuf-java",
        "@bazel_tools//third_party:junit4",
    ],
    size = "small",
)

java_test(
    name = "metrics_record_unittest",
    srcs = glob(["**/MetricsRecordTest.java"]),
    deps = [
        "//heron/api/src/java:api-java", 
        "//heron/common/src/java:common-java", 
        "//heron/metricsmgr-api/src/java:metricsmgr-api-java", 
        "//heron/metricsmgr/src/java:metricsmgr-lib-java", 
        "//heron/proto:proto-java",
        "//3rdparty/protobuf:protobuf-java",
        "@bazel_tools//third_party:junit4",
    ],
    size = "small",
)
