# packing algorithm for packing instances into containers
heron.class.packing.algorithm:    com.twitter.heron.packing.roundrobin.ResourceCompliantRRPacking
heron.class.repacking.algorithm:  com.twitter.heron.packing.roundrobin.ResourceCompliantRRPacking

# Instance CPU for Resource Packing
heron.resources.instance.cpu: 0.10
