# local state manager class for managing state in a persistent fashion
heron.class.state.manager:        com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager

# local state manager connection string
heron.statemgr.connection.string: "127.0.0.1:2181"

# path of the root address to store the state in a local file system
heron.statemgr.root.path:         "/heron"
