licenses(["notice"])

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "chart",
    srcs = glob(["templates/*.yaml"] + ["templates/*.txt"] + ["templates/*.tpl"] + ["*.lock"] + ["*.yaml"] + ["*.template"]) + ["//:disclaimers"],
)
