apiVersion: v1
description: Heron is a fast distributed streaming engine for processing large data volumes with velocity
name: heron
version: 0.1.0
appVersion: 0.17.0
icon: https://twitter.github.io/heron/img/HeronTextLogo-small.png
home: http://heron.io
sources:
  - https://github.com/twitter/heron.git
maintainers:
  - name: Karthik Ramasamy
    email: kramasamy@gmail.com
