package(default_visibility = ["//visibility:public"])

pex_library(
    name = "heron-integration-common-py",
    srcs = glob(["**/*.py"]),
    deps = [
        "//heronpy/api:heron-python-py",
    ],
)
