
pex_pytest(
    name = "opts_unittest",
    srcs = ["opts_unittest.py"],
    deps = [
        "//heron/cli/src/python:heron-lib",
    ],
    reqs = [
        "py==1.4.27",
        "pytest==2.6.4",
        "unittest2==0.5.1",
    ],
    size = "small",
)
