scala_test(
    name = "api-scala-test",
    srcs = glob(["org/apache/heron/streamlet/scala/**/*.scala"]),
    deps = [
        "//third_party/java:junit4",
        "//heron/api/src/scala:api-scala",
        "//heron/api/src/java:api-java",
        "//heron/api/src/java:api-java-low-level"
    ],
)