apiVersion: v1
kind: ReplicationController
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    app: minio
  template:
    metadata:
      name: minio
      labels:
        app: minio
    spec:
      containers:
        env:
        - name: MINIO_ACCESS_KEY
          value: YOUR_ACCESS_KEY_HERE
        - name: MINIO_SECRET_KEY
          value: YOUR_SECRET_KEY_HERE
      - name: minio
        image: minio/minio
        ports:
        - containerPort: 9000
