FROM ubuntu:16.04

ARG heronVersion

RUN apt-get update && apt-get -y install \
      curl \
      git \
      libssl-dev \
      libtool \
      libunwind8 \
      libunwind-setjmp0-dev \
      python \
      software-properties-common \
      unzip \
      wget \
      zip

RUN \
  echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
  add-apt-repository -y ppa:webupd8team/java && \
  apt-get update && \
  apt-get install -y oracle-java8-installer && \
  rm -rf /var/lib/apt/lists/* && \
  rm -rf /var/cache/oracle-jdk8-installer
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle

ADD artifacts /heron

WORKDIR /heron

#run heron installers
RUN /heron/heron-client-install-$heronVersion-ubuntu16.04.sh && \
    /heron/heron-tools-install-$heronVersion-ubuntu16.04.sh

RUN mkdir -p /opt/heron && \
    tar --strip-components=1 -zxvf /usr/local/heron/dist/heron-core.tar.gz -C /opt/heron

ENV HERON_HOME /opt/heron/heron-core/
RUN export HERON_HOME