FROM ubuntu:16.04

ARG heronVersion

RUN apt-get update && apt-get -y install \
      curl \
      git \
      libssl-dev \
      libtool \
      python \
      software-properties-common \
      unzip \
      wget \
      zip

RUN apt-get -y install openjdk-8-jdk

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64

ADD artifacts /heron

WORKDIR /heron

#run heron installers
RUN /heron/heron-client-install-$heronVersion-ubuntu16.04.sh && \
    /heron/heron-tools-install-$heronVersion-ubuntu16.04.sh

RUN mkdir -p /opt/heron && \
    tar --strip-components=1 -m -zxvf /usr/local/heron/dist/heron-core.tar.gz -C /opt/heron

ENV HERON_HOME /opt/heron/heron-core/
RUN export HERON_HOME
