FROM ubuntu:14.04

ARG heronVersion

RUN apt-get update 
RUN apt-get -y install python ; apt-get clean all
RUN apt-get -y install unzip ; apt-get clean all
RUN apt-get -y install software-properties-common ; apt-get clean all
RUN apt-get -y install curl ; apt-get clean all

RUN add-apt-repository ppa:openjdk-r/ppa && apt-get -y update
RUN apt-get -y install openjdk-8-jdk; apt-get clean all

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64

ADD artifacts /heron

WORKDIR /heron

# run heron installers
RUN /heron/heron-tools-install.sh

RUN mkdir -p /opt/heron && \
    tar --strip-components=1 -m -zxvf /heron/heron-core.tar.gz -C /opt/heron

RUN rm -f /heron/heron-tools-install.sh
RUN rm -f /heron/heron-core.tar.gz

ENV HERON_HOME /opt/heron/heron-core/
RUN export HERON_HOME
