# Topology health manager mode:
# disabled = do not launch the health manager
# cluster = launch the health manager on container-0
heron.topology.healthmgr.mode: disabled

# Default class and url for providing metrics
heron.healthmgr.metricsource.type: org.apache.heron.healthmgr.sensors.TrackerMetricsProvider
heron.healthmgr.metricsource.url: http://localhost:8888

# Enable MetricsCache if MetricsCache is chosen as metrics provider
#heron.topology.metricscachemgr.mode: cluster

## list of policies to be executed for self regulation
#heron.class.health.policies:
#  - dynamic-resource-allocation
#
## configuration specific to individual policies listed above
#dynamic-resource-allocation:
#  health.policy.class: org.apache.heron.healthmgr.policy.DynamicResourceAllocationPolicy
#  health.policy.interval.ms: 120000
#  BackPressureDetector.noiseFilterMillis: 20
#  GrowingWaitQueueDetector.limit: 5
