#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

# Docker 20.10.10 or older will not work
RUN apt-get update && apt-get -y install \
      ant \
      g++ \
      cmake \
      automake \
      libtool-bin \
      libunwind8 \
      patch \
      python-is-python3 \
      python3-dev \
      python3-venv \
      pkg-config \
      wget \
      zip \
      unzip \
      git \
      curl \
      tree \
      openjdk-11-jdk-headless

ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64

ENV bazelVersion 4.2.2

RUN wget -O /tmp/bazel.sh https://github.com/bazelbuild/bazel/releases/download/$bazelVersion/bazel-$bazelVersion-installer-linux-x86_64.sh \
      && chmod +x /tmp/bazel.sh \
      && /tmp/bazel.sh \
      && rm -rf /tmp/bazel.sh

ADD scripts/compile-platform.sh /compile-platform.sh
