FROM ubuntu:18.04

# This is passed to the heron build command via the --config flag
ENV TARGET_PLATFORM ubuntu
ENV bazelVersion 0.14.1

RUN apt-get update && apt-get -y install \
      g++ \
      cmake \
      automake \
      libtool-bin \
      libunwind8 \
      patch \
      python-dev \
      wget \
      zip \
      unzip

RUN apt-get -y install openjdk-8-jdk-headless

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64

RUN wget -O /tmp/bazel.sh https://github.com/bazelbuild/bazel/releases/download/$bazelVersion/bazel-$bazelVersion-installer-linux-x86_64.sh \
      && chmod +x /tmp/bazel.sh \
      && /tmp/bazel.sh

ADD bazelrc /root/.bazelrc
ADD scripts/compile-platform.sh /compile-platform.sh
