package(default_visibility = ["//visibility:public"])

java_binary(
    name='heron-examples-java',
    srcs = glob(["**/*.java"]),
    deps = [
        "//heron/api/src/java:api-java",
    ],
    create_executable = 0,
)
