# scheduler class for distributing the topology for execution
heron.class.scheduler:                       com.twitter.heron.scheduler.mesos.MesosScheduler

# launcher class for submitting and launching the topology
heron.class.launcher:                        com.twitter.heron.scheduler.mesos.MesosLauncher

# working directory for the topologies
heron.scheduler.mesos.scheduler.working.directory:     ${HOME}/.herondata/topologies/${CLUSTER}/${ROLE}/${TOPOLOGY}

# location of java - pick it up from shell environment
heron.directory.sandbox.java.home:           ${JAVA_HOME}

# The URI of Mesos Master
heron.mesos.master.uri:                      "127.0.0.1:5050"

# The maximum time in milliseconds waiting for MesosFramework got registered with Mesos Master
heron.mesos.framework.staging.timeout.ms:              2000

# The maximum time in milliseconds waiting for Mesos Scheduler Driver to complete stop()
heron.mesos.scheduler.driver.stop.timeout.ms:              5000

# the path to load native mesos library
heron.mesos.native.library.path:             "/usr/lib/mesos/0.28.1/lib/"

# location of the core package
heron.package.core.uri:                      file://${HOME}/.heron/dist/heron-core.tar.gz
