package(default_visibility = ["//visibility:public"])

filegroup(
    name = "example-vagrant-aurora",
    srcs = [
        "example/vagrant/aurora/aurora_bind.conf",
        "example/vagrant/aurora/aurora_scheduler.conf",
        "example/vagrant/aurora/cluster/devcluster.conf",
        "example/vagrant/aurora/heron.aurora",
        "example/vagrant/aurora/heron_controller.aurora"
    ],
)
