package(default_visibility = ["//visibility:public"])

filegroup(
    name = "com-twitter-aurora",
    srcs = [
        "com/twitter/aurora/aurora_bind.conf",
        "com/twitter/aurora/aurora_scheduler.conf",
        "com/twitter/aurora/cluster/atla.conf",
        "com/twitter/aurora/cluster/smf1.conf",
        "com/twitter/aurora/heron.aurora",
        "com/twitter/aurora/heron_controller.aurora"
    ],
)

filegroup(
    name = "example-vagrant-aurora",
    srcs = [
        "example/vagrant/aurora/aurora_bind.conf",
        "example/vagrant/aurora/aurora_scheduler.conf",
        "example/vagrant/aurora/cluster/devcluster.conf",
        "example/vagrant/aurora/heron.aurora",
        "example/vagrant/aurora/heron_controller.aurora"
    ],
)
