licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "config-cxx",
    srcs = ["empty.cc"],
    hdrs = [
        "heron-config.h",
    ],
    linkstatic = 1,
)
