package(default_visibility = ["//visibility:public"])

cc_test(
    name = "all-grouping_unittest",
    srcs = [
        "all-grouping_unittest.cpp",
    ],
    deps = [
        "//heron/stmgr/src/cpp:grouping-cxx",
        "//third_party/gtest:gtest-cxx",
    ],
    copts = [
        "-Iheron",
        "-Iheron/common/src/cpp",
        "-Iheron/stmgr/src/cpp",
        "-I$(GENDIR)/heron",
        "-I$(GENDIR)/heron/common/src/cpp",
    ],
    size = "small",
    linkstatic = 1,
)

cc_test(
    name = "custom-grouping_unittest",
    srcs = [
        "custom-grouping_unittest.cpp",
    ],
    deps = [
        "//heron/stmgr/src/cpp:grouping-cxx",
        "//third_party/gtest:gtest-cxx",
    ],
    copts = [
        "-Iheron",
        "-Iheron/common/src/cpp",
        "-Iheron/stmgr/src/cpp",
        "-I$(GENDIR)/heron",
        "-I$(GENDIR)/heron/common/src/cpp",
    ],
    size = "small",
    linkstatic = 1,
)

cc_test(
    name = "fields-grouping_unittest",
    srcs = [
        "fields-grouping_unittest.cpp",
    ],
    deps = [
        "//heron/stmgr/src/cpp:grouping-cxx",
        "//third_party/gtest:gtest-cxx",
    ],
    copts = [
        "-Iheron",
        "-Iheron/common/src/cpp",
        "-Iheron/stmgr/src/cpp",
        "-I$(GENDIR)/heron",
        "-I$(GENDIR)/heron/common/src/cpp",
    ],
    size = "small",
    linkstatic = 1,
)

cc_test(
    name = "lowest-grouping_unittest",
    srcs = [
        "lowest-grouping_unittest.cpp",
    ],
    deps = [
        "//heron/stmgr/src/cpp:grouping-cxx",
        "//third_party/gtest:gtest-cxx",
    ],
    copts = [
        "-Iheron",
        "-Iheron/common/src/cpp",
        "-Iheron/stmgr/src/cpp",
        "-I$(GENDIR)/heron",
        "-I$(GENDIR)/heron/common/src/cpp",
    ],
    size = "small",
    linkstatic = 1,
)

cc_test(
    name = "shuffle-grouping_unittest",
    srcs = [
        "shuffle-grouping_unittest.cpp",
    ],
    deps = [
        "//heron/stmgr/src/cpp:grouping-cxx",
        "//third_party/gtest:gtest-cxx",
    ],
    copts = [
        "-Iheron",
        "-Iheron/common/src/cpp",
        "-Iheron/stmgr/src/cpp",
        "-I$(GENDIR)/heron",
        "-I$(GENDIR)/heron/common/src/cpp",
    ],
    size = "small",
    linkstatic = 1,
)
