#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

FROM ubuntu:18.04

# This is passed to the heron build command via the --config flag
ENV TARGET_PLATFORM ubuntu
ENV bazelVersion 0.26.0


RUN apt-get update && apt-get -y install \
      g++ \
      cmake \
      automake \
      libtool-bin \
      libunwind8 \
      patch \
      python-dev \
      wget \
      zip \
      virtualenv \
      unzip \
      git \
      curl \
      openjdk-11-jdk-headless \
      tree \
      python-setuptools \
      python-dev \
      python-wheel \
      python \
      python-pip \
      curl \
      sudo

RUN curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -

RUN apt-get update && apt-get install -y nodejs

ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64

ARG UNAME
ARG UID
ARG GID
RUN groupadd -g $GID -o $UNAME
RUN useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME
USER $UNAME

RUN wget -O /tmp/bazel.sh https://github.com/bazelbuild/bazel/releases/download/$bazelVersion/bazel-$bazelVersion-installer-linux-x86_64.sh \
      && chmod +x /tmp/bazel.sh \
      && /tmp/bazel.sh --user

ADD bazelrc /home/$UNAME/.bazelrc
ENV PATH="/home/$UNAME/bin:${PATH}"

