package(default_visibility = ["//visibility:public"])

cc_test(
    name = "fileutils_unittest",
    srcs = ["fileutils_unittest.cpp"],
    deps = [
        "//heron/common/src/cpp/basics:basics-cxx",
        "//third_party/gtest:gtest-cxx",
    ],
    copts = [
        "-I.",
        "-Iheron/common/src/cpp",
    ],
    size = "small",
    linkstatic = 1,
)

cc_test(
    name = "rid_unittest",
    srcs = ["rid_unittest.cpp"],
    deps = [
        "//heron/common/src/cpp/basics:basics-cxx",
        "//third_party/gtest:gtest-cxx",
    ],
    copts = [
        "-I.",
        "-Iheron/common/src/cpp",
    ],
    size = "small",
    linkstatic = 1,
)

cc_test(
    name = "strutils_unittest",
    srcs = ["strutils_unittest.cpp"],
    deps = [
        "//heron/common/src/cpp/basics:basics-cxx",
        "//third_party/gtest:gtest-cxx",
    ],
    copts = [
        "-I.",
        "-Iheron/common/src/cpp",
    ],
    size = "small",
    linkstatic = 1,
)

cc_test(
    name = "utils_unittest",
    srcs = ["utils_unittest.cpp"],
    deps = [
        "//heron/common/src/cpp/basics:basics-cxx",
        "//third_party/gtest:gtest-cxx",
    ],
    copts = [
        "-I.",
        "-Iheron/common/src/cpp",
    ],
    size = "small",
    linkstatic = 1,
)
