#ifndef _CORE_SRC_CPP_NEWTORK_NETWORK_ERROR_H_
#define _CORE_SRC_CPP_NEWTORK_NETWORK_ERROR_H_

enum NetworkErrorCode {
  OK = 0,
  CONNECT_ERROR,
  READ_ERROR,
  WRITE_ERROR,
  CLOSE_ERROR,
  INVALID_CONNECTION,
  DUPLICATE_START,
  INVALID_PACKET,
  DUPLICATE_PACKET_ID,
  TIMEOUT
};

#endif  // _CORE_SRC_CPP_NEWTORK_NETWORK_ERROR_H_