# scheduler class for distributing the topology for execution
heron.class.scheduler:                       com.twitter.heron.scheduler.aurora.AuroraScheduler

# launcher class for submitting and launching the topology
heron.class.launcher:                        com.twitter.heron.scheduler.aurora.AuroraLauncher

# location of java - pick it up from shell environment
heron.directory.sandbox.java.home:           /usr/lib/jvm/java-1.8.0-openjdk-amd64/

# Invoke the IScheduler as a library directly
heron.scheduler.is.service:                  False

####################################################################
# Following are Aurora-specific
####################################################################
# The maximum retry attempts when trying to kill an Aurora job
heron.scheduler.job.max.kill.attempts:       5

# The interval in ms between two retry-attempts to kill an Aurora job
heron.scheduler.job.kill.retry.interval.ms:  2000

# Aurora Controller Class
# heron.class.scheduler.aurora.controller.cli:     False

####################################################################
# Following are config for tunneling
####################################################################
# Whether we should attempt to tunnel if there is no direct access to a remote host (e.g. TMaster)
heron.scheduler.is.tunnel.needed:                          False

# The connection timeout in ms when testing if we can connect to remote host
heron.scheduler.tunnel.connection.timeout.ms:              1000

# The number of retries when testing direct access to remote host
heron.scheduler.tunnel.connection.retry.count:             2

# The interval in ms between two retries when testing direct access to remote host
heron.scheduler.tunnel.retry.interval.ms:                  1000

# The number of retries when verifying connectivity via tunnel
heron.scheduler.tunnel.verify.count:                       10

# SSH tunnel host
heron.scheduler.tunnel.host:                               "my.tunnel.host"
