#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# local state manager class for managing state in a persistent fashion
heron.class.state.manager:                      org.apache.heron.statemgr.localfs.LocalFileSystemStateManager

# local state manager connection string
heron.statemgr.connection.string:               LOCALMODE

# path of the root address to store the state in a local file system
heron.statemgr.root.path:                       /vagrant/.herondata/repository/state/${CLUSTER}

# create the sub directories, if needed
heron.statemgr.localfs.is.initialize.file.tree: True

####################################################################
# Following are config for tunneling
####################################################################
# Whether we should attempt to tunnel if there is no direct access to a remote host (e.g. Zookeeper)
heron.statemgr.is.tunnel.needed:                          False

# The connection timeout in ms when testing if we can connect to remote host
heron.statemgr.tunnel.connection.timeout.ms:              1000

# The number of retries when testing direct access to remote host
heron.statemgr.tunnel.connection.retry.count:             2

# The interval in ms between two retries when testing direct access to remote host
heron.statemgr.tunnel.retry.interval.ms:                  1000

# The number of retries when verifying connectivity via tunnel
heron.statemgr.tunnel.verify.count:                       10

# SSH tunnel host
heron.statemgr.tunnel.host:                               "my.tunnel.host"
