# uploader class for transferring the topology jar/tar files to storage
heron.class.uploader:                            com.twitter.heron.uploader.http.HttpUploader

heron.uploader.http.uri:                         <http_uploader_uri>

