# uploader class for transferring the topology jar/tar files to storage
heron.class.uploader:                            org.apache.heron.uploader.http.HttpUploader

heron.uploader.http.uri:                          http://localhost:9000/api/v1/file/upload

