licenses(["notice"])

package(default_visibility = ["//visibility:public"])

sh_binary(
    name = "env_exec",
    srcs = ["env_exec.sh"],
)

sh_binary(
    name = "gen_errcodes",
    srcs = ["errors.sh"],
)
