package(default_visibility = ["//visibility:public"])

cc_test(
    name = "count-metric_unittest",
    srcs = [
        "count-metric_unittest.cpp",
    ],
    deps = [
        "//heron/common/src/cpp/metrics:metrics-cxx",
        "//third_party/gtest:gtest-cxx",
    ],
    copts = [
        "-Iheron",
        "-Iheron/common/src/cpp",
        "-I$(GENDIR)/heron",
        "-I$(GENDIR)/heron/common/src/cpp",
    ],
    size = "small",
    linkstatic = 1,
)

cc_test(
    name = "mean-metric_unittest",
    srcs = [
        "mean-metric_unittest.cpp",
    ],
    deps = [
        "//heron/common/src/cpp/metrics:metrics-cxx",
        "//third_party/gtest:gtest-cxx",
    ],
    copts = [
        "-Iheron",
        "-Iheron/common/src/cpp",
        "-I$(GENDIR)/heron",
        "-I$(GENDIR)/heron/common/src/cpp",
    ],
    size = "small",
    linkstatic = 1,
)

cc_test(
    name = "multi-count-metric_unittest",
    srcs = [
        "multi-count-metric_unittest.cpp",
    ],
    deps = [
        "//heron/common/src/cpp/metrics:metrics-cxx",
        "//third_party/gtest:gtest-cxx",
    ],
    copts = [
        "-Iheron",
        "-Iheron/common/src/cpp",
        "-I$(GENDIR)/heron",
        "-I$(GENDIR)/heron/common/src/cpp",
    ],
    size = "small",
    linkstatic = 1,
)

cc_test(
    name = "multi-mean-metric_unittest",
    srcs = [
        "multi-mean-metric_unittest.cpp",
    ],
    deps = [
        "//heron/common/src/cpp/metrics:metrics-cxx",
        "//third_party/gtest:gtest-cxx",
    ],
    copts = [
        "-Iheron",
        "-Iheron/common/src/cpp",
        "-I$(GENDIR)/heron",
        "-I$(GENDIR)/heron/common/src/cpp",
    ],
    size = "small",
    linkstatic = 1,
)

cc_test(
    name = "time-spent-metric_unittest",
    srcs = [
        "time-spent-metric_unittest.cpp",
    ],
    deps = [
        "//heron/common/src/cpp/metrics:metrics-cxx",
        "//third_party/gtest:gtest-cxx",
    ],
    copts = [
        "-Iheron",
        "-Iheron/common/src/cpp",
        "-I$(GENDIR)/heron",
        "-I$(GENDIR)/heron/common/src/cpp",
    ],
    size = "small",
    linkstatic = 1,
)
