java_library(
    name = "heron-kafka-java",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@kafka-clients-java//jar",
        "@json-simple//jar",
        "@gson-java//jar",
        "@slf4j-api//jar",
        "@curator-framework//jar",
        "@curator-client//jar",
        "@guava//jar",
        "//3rdparty/java:zookeeper-java-nl",
        "//heron/api/src/java:api-java-nl",
    ],
)
