java_library(
    name = "heron-kafka-java",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//3rdparty/kafka:kafka-clients-java",
        "//3rdparty/json-simple:json-simple-java",
        "//3rdparty/gson:gson-java",
        "//3rdparty/logging:slf4j-api-java",
        "//3rdparty/curator:curator-java",
        "//3rdparty/guava:guava-java",
        "//3rdparty/zookeeper:zookeeper-java-neverlink",
        "//heron/api/src/java:api-java-nl",
    ],
)
