licenses(["notice"])

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "config-internals-yaml",
    srcs = ["heron_internals.yaml"],
)

filegroup(
    name = "metrics-sinks-yaml",
    srcs = ["metrics_sinks.yaml"],
)

filegroup(
    name = "test-config-internals-yaml",
    srcs = ["test_heron_internals.yaml"],
)

filegroup(
    name = "conf-yaml",
    srcs = glob(["conf/*.yaml"]),
)

filegroup(
    name = "conf-local-yaml",
    srcs = glob(["conf/local/*.yaml"]),
)

filegroup(
    name = "conf-aurora-yaml",
    srcs = glob(["conf/aurora/*"]),
)

filegroup(
    name = "conf-local-heron-internals",
    srcs = ["conf/local/heron_internals.yaml"],
)

filegroup(
    name = "conf-local-metrics-sinks",
    srcs = ["conf/local/metrics_sinks.yaml"],
)

filegroup(
    name = "conf-local-packing",
    srcs = ["conf/local/packing.yaml"],
)

filegroup(
    name = "conf-local-scheduler",
    srcs = ["conf/local/scheduler.yaml"],
)

filegroup(
    name = "conf-local-statemgr",
    srcs = ["conf/local/statemgr.yaml"],
)

filegroup(
    name = "conf-local-uploader",
    srcs = ["conf/local/uploader.yaml"],
)
