licenses(["notice"])

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "config-internals-yaml",
    srcs = ["heron_internals.yaml"],
)

filegroup(
    name = "metrics-sinks-yaml",
    srcs = ["metrics_sinks.yaml"],
)

filegroup(
    name = "test-config-internals-yaml",
    srcs = ["test_heron_internals.yaml"],
)
