licenses(["notice"])

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "config-keys-yaml",
    srcs = ["keys.yaml"],
)

filegroup(
    name = "config-defaults-yaml",
    srcs = ["defaults.yaml"],
)

filegroup(
    name = "config-internals-yaml",
    srcs = ["heron_internals.yaml"],
)

filegroup(
    name = "metrics-sinks-yaml",
    srcs = ["metrics_sinks.yaml"],
)

filegroup(
    name = "test-config-internals-yaml",
    srcs = ["test_heron_internals.yaml"],
)

filegroup(
    name = "conf-yaml",
    srcs = glob(["conf/*.yaml"]),
)

filegroup(
    name = "conf-local-yaml",
    srcs = glob(["conf/local/*.yaml"]),
)
