package(default_visibility = ["//visibility:public"])

cc_library(
    name = "libhdfs3-cxx",
    srcs = ["empty.cc"],
    deps = [
        "//heron/storage/src/cpp/libhdfs3/common:common-cxx",
        "//heron/storage/src/cpp/libhdfs3/network:network-cxx",
        "//heron/storage/src/cpp/libhdfs3/rpc:rpc-cxx",
        "//heron/storage/src/cpp/libhdfs3/server:server-cxx",
    ],
    linkstatic = 1,
)
