# packing algorithm for packing instances into containers
heron.class.packing.algorithm:    org.apache.heron.packing.roundrobin.ResourceCompliantRRPacking
heron.class.repacking.algorithm:  org.apache.heron.packing.roundrobin.ResourceCompliantRRPacking
