# scheduler class for distributing the topology for execution
heron.class.scheduler:                       com.twitter.heron.scheduler.aurora.AuroraScheduler

# launcher class for submitting and launching the topology
heron.class.launcher:                        com.twitter.heron.scheduler.aurora.AuroraLauncher

# location of java - pick it up from shell environment
heron.directory.sandbox.java.home:           /usr/lib/jvm/java-1.8.0-openjdk-amd64/

# Invoke the IScheduler as a library directly
heron.scheduler.is.service:                  False

