package(default_visibility = ["//visibility:public"])

filegroup(
    name = "templates",
    srcs = glob(["templates/**/*.html"]),
)

filegroup(
    name = "static",
    srcs = glob(["static/**/*"]),
)
